"""flag_flip_proposals (Phase 5.C session 1)

Revision ID: p5c5r6s7t8u9
Revises: p5a4q5r6s7t8
Create Date: 2026-08-14 23:45:00.000000+00:00

Records proposed environment-flag flips generated by the daily
autonomous_flag_manager runner. Session 1 fills this table but
never auto-applies — session 2 adds the 24h override window +
auto-apply.

Row shape:
  * ``flag_name`` — e.g. ``GENLAB_STYLE_GUIDANCE_ROLLOUT_PCT``
  * ``from_state`` / ``to_state`` — string representations (env
    values are strings anyway); keeps type-erasure simple.
  * ``rationale`` — human-readable why-string with pinned
    evidence citations.
  * ``evidence`` JSONB — the raw signal snapshot that drove the
    proposal (analyzer output, thresholds, sample counts).
  * ``confidence`` — [0, 1]; session 2 auto-applies at > 0.9.
  * ``status`` — pending / applied / rejected / superseded.
    Superseded when a later proposal for the same flag replaces
    a pending one.
  * ``applied_at`` / ``applied_by`` — filled when session-2 runner
    performs the flip. applied_by = 'auto' or 'operator'.
  * ``rejected_at`` / ``rejection_reason`` — filled by operator
    override.

Rule #22 discipline: rationale MUST include the confusion-matrix
or lift-percentage breakdown that supports the flip, not just an
aggregate. This lets the operator eyeball the evidence in one line.
"""
from alembic import op

revision = "p5c5r6s7t8u9"
down_revision = "p5a4q5r6s7t8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS flag_flip_proposals (
            id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            flag_name TEXT NOT NULL,
            from_state TEXT NOT NULL,
            to_state TEXT NOT NULL,
            rationale TEXT NOT NULL,
            evidence JSONB NOT NULL DEFAULT '{}'::jsonb,
            confidence DOUBLE PRECISION NOT NULL,
            status TEXT NOT NULL DEFAULT 'pending'
              CHECK (status IN ('pending', 'applied', 'rejected', 'superseded')),
            proposed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            applied_at TIMESTAMPTZ,
            applied_by TEXT,
            rejected_at TIMESTAMPTZ,
            rejection_reason TEXT
        )
        """
    )
    op.execute(
        """
        CREATE INDEX IF NOT EXISTS ix_flag_flip_proposals_flag_status
        ON flag_flip_proposals (flag_name, status, proposed_at DESC)
        """
    )
    op.execute(
        """
        CREATE INDEX IF NOT EXISTS ix_flag_flip_proposals_pending
        ON flag_flip_proposals (proposed_at DESC)
        WHERE status = 'pending'
        """
    )


def downgrade() -> None:
    op.execute("DROP INDEX IF EXISTS ix_flag_flip_proposals_pending")
    op.execute("DROP INDEX IF EXISTS ix_flag_flip_proposals_flag_status")
    op.execute("DROP TABLE IF EXISTS flag_flip_proposals")
