"""What each shot of an anime reel IS, and where its picture comes from.

ANIME-13 §5. The order is the anime-edit grammar from the benchmark:

    PV cold open -> hook card -> cover on the title beat -> PV moment on the
    first turn -> character still on the name -> PV moment -> connective
    still -> card -> PV moment -> outro over the banner, loop-back.

Two rules do the real work, and neither needs a threshold:

* **A shot showing the show beats a shot describing it.** The order above is
  a preference list: PV, then the show's own art, then a character portrait,
  and a generated picture only where none of those fits.
* **A generated still requires the cover as an image reference.** No cover,
  no generated still — a PV frame is used instead. The palette distance is
  measured and recorded but never blocks; it fails its own positive control
  (see ``palette_match``).

Degradation is explicit at every step, because the material is uneven: of the
top 40 FALL-2026 shows only 13 have a banner, and ``episodes`` is routinely
null months before air. A grammar that assumes a full set produces a reel for
the minority of shows.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from typing import Any

from genlab_core.still.beats import Beat, Storyboard
from genlab_core.still.pv import PVMoment
from genlab_core.still.sourcing import ShowArt

logger = logging.getLogger(__name__)

# Where a shot's picture comes from. Ordered by how directly it shows the
# show, which is also the preference order.
PV_COLD = "pv_cold_open"
PV_PEAK = "pv_peak"
PV_SLATE = "pv_slate"
COVER = "cover"
BANNER = "banner"
CHARACTER = "character"
GENERATED = "generated_with_reference"
PV_FRAME = "pv_frame"
CARD = "card"

#: Which origins are the show's own material, for the per-shot table.
OWN_MATERIAL = frozenset({PV_COLD, PV_PEAK, PV_SLATE, COVER, BANNER, CHARACTER, PV_FRAME})

#: Rights posture per origin. Footage and key art are the rights-bearing ones
#: and both carry the attribution slate; a generated picture is ours.
RIGHTS = {
    PV_COLD: "official PV — attribution slate",
    PV_PEAK: "official PV — attribution slate",
    PV_SLATE: "official PV — attribution slate",
    PV_FRAME: "official PV — attribution slate",
    COVER: "key art — attribution slate",
    BANNER: "key art — attribution slate",
    CHARACTER: "key art — attribution slate",
    GENERATED: "generated (ours)",
    CARD: "AniList facts, drawn locally (ours)",
}


@dataclass
class Shot:
    """One shot of the reel: what it shows and why it was chosen."""

    index: int
    origin: str
    duration_s: float
    beat_index: int | None = None
    #: A PV window, a URL, or a prompt — whichever the origin implies.
    moment: PVMoment | None = None
    url: str = ""
    prompt: str = ""
    reference_url: str = ""
    attribution: str = ""
    notes: str = ""
    extra: dict[str, Any] = field(default_factory=dict)

    @property
    def is_own_material(self) -> bool:
        return self.origin in OWN_MATERIAL

    @property
    def rights(self) -> str:
        return RIGHTS.get(self.origin, "unknown")

    def row(self) -> str:
        what = self.url or self.prompt or (f"PV {self.moment.start_s:.2f}s" if self.moment else "")
        return f"  {self.index:2d}  {self.origin:<24} {self.duration_s:4.2f}s  {what[:52]}"


def _build_prompt(beat: Beat, kit: dict[str, Any]) -> str:
    """The kit's ONE template, plus the avoid list folded into the prompt.

    ``pruna/flux-2-klein-4b`` has no ``negative_prompt`` field. The kit
    carried one and the ANIME-12 driver computed it into a local variable and
    never sent it, so every still ever generated by this path ran with no
    negative at all. Folding it into the prompt is the only way this model can
    receive it.
    """
    sp = kit["still_prompt"]
    pal = kit["palette"]
    base = sp["template"].format(beat=beat.text.rstrip(". "), palette=pal["description"].strip())
    return f"{base} Avoid: {pal['avoid'].strip()}"


def plan_shots(
    board: Storyboard,
    art: ShowArt,
    *,
    cold: PVMoment | None = None,
    peaks: list[PVMoment] | None = None,
    slate: PVMoment | None = None,
    card_s: float = 2.0,
    kit: dict[str, Any] | None = None,
) -> list[Shot]:
    """The shot list, in order, with every degradation named in ``notes``."""
    kit = kit or board.kit
    peaks = list(peaks or [])
    shots: list[Shot] = []
    used_characters: set[str] = set()
    idx = 0

    def add(**kw) -> Shot:
        nonlocal idx
        s = Shot(index=idx, **kw)
        shots.append(s)
        idx += 1
        return s

    # ── 1. Cold open: one second of the PV, under the hook card ───────────
    if cold is not None:
        add(
            origin=PV_COLD,
            duration_s=cold.duration_s,
            moment=cold,
            attribution=art.attribution,
            notes="hook card overlays this",
        )
    elif art.cover:
        add(
            origin=COVER,
            duration_s=1.2,
            url=art.cover,
            attribution=art.attribution,
            notes="no PV — cover stands in as the cold open",
        )
    else:
        logger.warning("[grammar] no PV and no cover: the reel opens on a generated still")

    # ── 2..n. One slot per beat, cycling the grammar's preference order ───
    peak_i = 0
    for beat in board.beats:
        dur = beat.shot_s
        character = art.character_for(beat.text)

        # A beat that NAMES a character gets that character's portrait. This
        # is the single most recognisable image for that line and it needs no
        # model to produce.
        if character and character["name"] not in used_characters:
            used_characters.add(character["name"])
            add(
                origin=CHARACTER,
                duration_s=dur,
                beat_index=beat.index,
                url=character["image_url"],
                attribution=art.attribution,
                notes=f"beat names {character['name']}",
            )
            continue

        # The title beat — the first one — shows the key art.
        if beat.index == 0 and art.cover:
            add(
                origin=COVER,
                duration_s=dur,
                beat_index=beat.index,
                url=art.cover,
                attribution=art.attribution,
                notes="title beat",
            )
            continue

        # Everything else prefers PV footage while any remains.
        if peak_i < len(peaks):
            m = peaks[peak_i]
            peak_i += 1
            add(
                origin=PV_PEAK,
                duration_s=dur,
                beat_index=beat.index,
                moment=m,
                attribution=art.attribution,
            )
            continue

        # Connective tissue. A generated still ONLY with the cover as
        # reference; otherwise a frame of the PV.
        if art.cover:
            add(
                origin=GENERATED,
                duration_s=dur,
                beat_index=beat.index,
                prompt=_build_prompt(beat, kit),
                reference_url=art.cover,
                notes="connective — generated with the cover as reference",
            )
        else:
            add(
                origin=PV_FRAME,
                duration_s=dur,
                beat_index=beat.index,
                attribution=art.attribution,
                notes="no cover, so no generated still — a PV frame instead",
            )

    # ── The end slate, if the PV had one ──────────────────────────────────
    if slate is not None:
        add(
            origin=PV_SLATE,
            duration_s=slate.duration_s,
            moment=slate,
            attribution=art.attribution,
            notes="broadcast slate, letterboxed",
        )

    # ── The card, which also carries the outro ────────────────────────────
    add(
        origin=CARD,
        duration_s=card_s,
        url=art.banner or art.cover,
        notes="AniList facts + handle; banner behind it"
        if art.banner
        else "AniList facts + handle; no banner, flat card",
    )

    n_own = sum(1 for s in shots if s.is_own_material)
    logger.info(
        "[grammar] %d shots, %d of the show's own material (%d PV, %d key art), %d generated",
        len(shots),
        n_own,
        sum(1 for s in shots if s.origin in (PV_COLD, PV_PEAK, PV_SLATE, PV_FRAME)),
        sum(1 for s in shots if s.origin in (COVER, BANNER, CHARACTER)),
        sum(1 for s in shots if s.origin == GENERATED),
    )
    for s in shots:
        logger.info("%s", s.row())
    return shots
