#!/bin/bash
# ensure_yt_dlp_environment.sh — idempotent pre-pipeline setup.
#
# Task #35 (2026-06-13). Runs as `ExecStartPre` for every pipeline
# systemd unit. Bakes in the two prod hotfixes from 2026-06-12 so
# they survive future deploys instead of evaporating:
#
#   1. /usr/local/bin/yt-dlp wrapper — the venv installs `yt-dlp` as
#      a Python module but does NOT create a console_script entry,
#      so `subprocess.run(["yt-dlp", ...])` from the pipeline fails
#      with FileNotFoundError. A 4-line wrapper at /usr/local/bin/
#      forwards to `python -m yt_dlp` and survives venv rebuilds.
#
#   2. /opt/genlab/.youtube_cookies.txt ownership — yt-dlp reads the
#      cookies file (mode 644 works) but tries to UPDATE it at end
#      of session. If the file is owned by root (which happens when
#      the operator initially places it via scp), yt-dlp's write
#      fails → exit non-zero → pipeline interprets as "download
#      failed" even though the MP4 actually downloaded fine. Chown
#      to genlab:genlab fixes this.
#
# Pre-fix (2026-05-21 → 2026-06-12), both hotfixes evaporated on
# any code redeploy because they lived only on the prod box. The
# 22-day "0 published / $2 burned" outage traced back partly to
# this. See [[session-2026-06-12-outage-remediation]].
#
# Idempotent — safe to run every pipeline start. Fast (~5ms). Never
# fails the systemd unit even on partial errors — logs to journal
# and lets the pipeline proceed (with the existing CRITICAL alerts
# catching any actual breakage downstream).
#
# Test:
#   bash deploy/scripts/ensure_yt_dlp_environment.sh
#   ls -la /usr/local/bin/yt-dlp
#   /usr/local/bin/yt-dlp --version

set -uo pipefail  # NOT -e: we want to log and continue, not abort the pipeline

# ── Paths (matches prod layout) ────────────────────────────────────────────
GENLAB_ROOT="${GENLAB_PROJECT_ROOT:-/opt/genlab}"
VENV_PYTHON="${GENLAB_ROOT}/.venv/bin/python"
YT_DLP_WRAPPER="/usr/local/bin/yt-dlp"
COOKIES_FILE="${GENLAB_ROOT}/.youtube_cookies.txt"
SESSION_FILE="${GENLAB_ROOT}/.youtube_session.json"

log() {
  # Use systemd's journal format (no timestamp prefix; systemd adds one).
  echo "[ensure_yt_dlp_environment] $*" >&2
}

# ── 1. yt-dlp wrapper ──────────────────────────────────────────────────────
desired_wrapper_content="#!/bin/bash
# Auto-generated by deploy/scripts/ensure_yt_dlp_environment.sh
# Forwards to python -m yt_dlp because the venv doesn't install a
# console_script. Edit the source script if you need to change this.
exec ${VENV_PYTHON} -m yt_dlp \"\$@\"
"

# Only rewrite if the wrapper is missing or has different content. Avoids
# pointless writes that could race with a concurrent invocation.
if [[ ! -f "$YT_DLP_WRAPPER" ]] || ! cmp -s <(printf '%s' "$desired_wrapper_content") "$YT_DLP_WRAPPER"; then
  if printf '%s' "$desired_wrapper_content" | tee "$YT_DLP_WRAPPER" >/dev/null 2>&1; then
    chmod 755 "$YT_DLP_WRAPPER" 2>/dev/null || true
    log "wrote yt-dlp wrapper at $YT_DLP_WRAPPER"
  else
    log "WARN: could not write yt-dlp wrapper (need root?); pipeline will likely fail downloads"
  fi
else
  log "yt-dlp wrapper already current at $YT_DLP_WRAPPER"
fi

# ── 2. Cookies + session file ownership ───────────────────────────────────
fix_ownership() {
  local path="$1"
  if [[ -f "$path" ]]; then
    local owner
    owner="$(stat -c '%U:%G' "$path" 2>/dev/null || stat -f '%Su:%Sg' "$path" 2>/dev/null || echo unknown)"
    if [[ "$owner" != "genlab:genlab" ]]; then
      if chown genlab:genlab "$path" 2>/dev/null; then
        log "chowned $path (was $owner)"
      else
        log "WARN: could not chown $path (was $owner); yt-dlp may fail to update cookies"
      fi
    fi
  fi
}

fix_ownership "$COOKIES_FILE"
fix_ownership "$SESSION_FILE"

# ── 3. uv binary visibility under HOME=/opt/genlab ────────────────────────
# scripts/daily_intel.sh now resolves uv via `command -v` first
# (PR-fixed 2026-06-14), but historical callers + the operator's
# scripts may still hardcode `${HOME}/.local/bin/uv`. Under systemd's
# Environment=HOME=/opt/genlab, that path resolves to
# /opt/genlab/.local/bin/uv — which is empty on a fresh box (uv
# installs to /usr/local/bin or /root/.local/bin). Symlink it so the
# legacy path also works.
#
# Self-healing — the 2026-06-14 deploy-pipeline-gap recovery
# discovered prod was missing this symlink. We patched manually then;
# this bakes it into the pre-pipeline lifecycle so future fresh
# boxes never hit the same regression.
ensure_uv_legacy_symlink() {
  local target src
  src="$(command -v uv 2>/dev/null || true)"
  if [[ -z "$src" ]]; then
    for candidate in /usr/local/bin/uv /root/.local/bin/uv; do
      if [[ -x "$candidate" ]]; then src="$candidate"; break; fi
    done
  fi
  if [[ -z "$src" ]]; then
    log "WARN: uv binary not found anywhere; skipping legacy symlink"
    return
  fi
  target="${GENLAB_ROOT}/.local/bin/uv"
  if [[ -L "$target" ]] && [[ "$(readlink "$target")" == "$src" ]]; then
    return  # already correct, no-op
  fi
  if mkdir -p "$(dirname "$target")" 2>/dev/null && ln -sfn "$src" "$target" 2>/dev/null; then
    chown -h genlab:genlab "$target" 2>/dev/null || true
    log "uv legacy symlink: $target → $src"
  else
    log "WARN: could not create uv legacy symlink at $target"
  fi
}
ensure_uv_legacy_symlink

# Always exit 0 — never block the pipeline on a setup-script hiccup. The
# real-failure detection lives in the alerts pipeline (CriticalAlertsBanner,
# pipeline_alerts.download_failure, etc.) which catches anything we missed.
exit 0
