"""Pin: deploy.sh auto-resets dashboard/frontend/package-lock.json
drift before the dirty-tree check.

Background: when a Dependabot frontend-dep bump merges and the operator
runs `npm install` on prod to pull the new packages, npm rewrites the
lockfile with cosmetic binary-hash differences. Subsequent
`deploy.sh --apply` runs then fail the dirty-tree check on the single
"M dashboard/frontend/package-lock.json" line — even though that file
will be overwritten by the upcoming git pull + regenerated by the
next npm install anyway.

Hit on 2026-06-26 twice (Dependabot batch #595-#599 + the chain trying
to deploy PR #603 afterward). Forced manual `git checkout --
package-lock.json` workarounds both times.

This pin locks in the auto-reset behavior so a future refactor that
removes it surfaces in CI before it bites prod again.
"""

from __future__ import annotations

from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
DEPLOY_SH = REPO_ROOT / "scripts" / "deploy.sh"


class TestLockfileDriftReset:
    def test_deploy_sh_auto_resets_package_lock_json(self):
        """deploy.sh MUST contain a `git checkout -- dashboard/frontend/
        package-lock.json` call BEFORE the dirty-tree check fires.
        This is the load-bearing line that lets prod self-recover from
        npm-install-rewrote-the-lockfile state without operator
        intervention."""
        content = DEPLOY_SH.read_text()
        assert "git checkout -- dashboard/frontend/package-lock.json" in content, (
            "deploy.sh must auto-reset dashboard/frontend/package-lock.json "
            "before the dirty-tree check. Without it, prod gets stuck "
            "after every Dependabot frontend bump because npm install "
            "rewrites the lockfile cosmetically. Removed in a refactor? "
            "Re-add it or replace with an equivalent narrow-scoped reset."
        )

    def test_lockfile_reset_appears_before_dirty_tree_check(self):
        """The auto-reset must come BEFORE the `git diff --quiet`
        check, otherwise the check fires first and the reset never
        executes. Order matters."""
        content = DEPLOY_SH.read_text()
        reset_pos = content.find("git checkout -- dashboard/frontend/package-lock.json")
        dirty_check_pos = content.find('fail "working tree')
        assert reset_pos > 0, "auto-reset line missing entirely"
        assert dirty_check_pos > 0, "dirty-tree fail line missing"
        assert reset_pos < dirty_check_pos, (
            f"auto-reset (pos={reset_pos}) must come BEFORE dirty-tree "
            f"check (pos={dirty_check_pos}). Order reversed means the "
            f"check fires first and the reset never runs."
        )

    def test_dirty_check_error_clarifies_untracked_does_not_block(self):
        """The error message after the dirty-tree check should make
        clear that untracked files (e.g., .bak leftovers) do NOT
        block deploy — only modified tracked files do. This is the
        operator-facing clarification that prevents 'I have .bak
        files, is THAT why deploy failed?' confusion (the actual cause
        is always a tracked modification, never untracked)."""
        content = DEPLOY_SH.read_text()
        # Either the "dirty files" log header OR the fail message
        # should mention that untracked files are not the issue.
        markers = [
            "untracked .bak files do not block deploy",
            "tracked modifications only",
            "tracked",  # at minimum the fail message should say "tracked"
        ]
        assert any(m in content for m in markers), (
            "deploy.sh dirty-tree error/log should clarify that only "
            "tracked modifications cause the failure (untracked files "
            "do not). Otherwise operators waste time chasing .bak file "
            "cleanups when the real cause is one modified tracked file."
        )
